# fly.toml app configuration file generated for monitor-sw7lsq on 2026-05-09T08:33:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monitor-sw7lsq'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
